In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits = load_digits()

In [2]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [6]:
digits.feature_names[:5]

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4']

In [7]:
digits.frame

In [11]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [12]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x = digits.data
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [14]:
y = digits.target
y

array([0, 1, 2, ..., 8, 9, 8])

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

# Logistic Regression

In [16]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9574074074074074

In [17]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

c:\users\dell1\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

# SVM

In [19]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.36666666666666664

In [18]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

# Random Forest

In [20]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9777777777777777

# KFold cross validation
Basic example

In [43]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [44]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [45]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [46]:
get_score(LogisticRegression(),X_train, X_test, y_train, y_test)

c:\users\dell1\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [47]:
get_score(SVC(),X_train, X_test, y_train, y_test)

0.9907407407407407

In [48]:
get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test)

0.9777777777777777

In [49]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []


for train_index, test_index in folds.split(x,y):
    X_train, X_test, y_train, y_test = x[train_index], x[test_index], \
                                       y[train_index], y[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))








In [50]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [51]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [52]:
scores_rf

[0.9215358931552587, 0.9382303839732888, 0.9165275459098498]

# cross_val_score function

In [53]:
from sklearn.model_selection import cross_val_score

In [ ]:
# Logistic regression model performance using cross_val_score

In [54]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x, y,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

# svm model performance using cross_val_score

In [55]:
cross_val_score(SVC(gamma='auto'), x, y,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

# random forest performance using cross_val_score

In [56]:
cross_val_score(RandomForestClassifier(n_estimators=40), x, y,cv=3)

array([0.94490818, 0.94156928, 0.9148581 ])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=40), x, y,cv=5)

array([0.93333333, 0.89444444, 0.95264624, 0.96100279, 0.92479109])

# Parameter tunning using k fold cross validation

In [57]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),x, y, cv=10)
np.average(scores1)

0.8876070763500931

In [58]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),x, y, cv=10)
np.average(scores2)

0.9387895716945994

In [62]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9404562383612662

In [61]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9448944754810675